### ISSUE TITLE
False negative if Mailbox is on premise

### ISSUE THREAD

**Issue by bandrel** [Raikia/UhOh365#1]
The logic for if the account is valid is slightly flawed. From my testing a valid user with a valid mailbox hosted in o365 will return an HTTP 200 as documented. However, if the user is valid, but the mailbox for a user is still hosted on premise a 302 will be returned with the message 'Object moved to' where the URL specified is the on premise hostname and not outlook.office365.com.

**Comment by Raikia** [comment]
Correct, it only tests for valid o365-specific email accounts.  You are right in that the 302 "Location" attribute points to the on-prem version, but the on-prem versions differ heavily on its enumeration capability and can't rely on this same process.  I actually have some additional research to target on-prem exchange that I will be adding to this script shortly to address that, but it has to take into account various exchange versions and response codes for each one.

Also, the 302 "location" is not fully reliable.  From my testing, that location simply takes whatever is after the "@", appends "autodiscover." to it and sends the user there. So if you run it against "test@oerigjaoeirgmoaei.com", it will redirect to "autodiscover.oerigjaoeirgmoaei.com", which does not exist.


There are ways to enumerate on-prem email accounts using similar methods which is "coming soon" to this script :-)

**Comment by Raikia** [comment]
Teamwork makes the dream work.  See if my addition to your pull request fixes this in your test cases
