### ISSUE TITLE
Support for suffix email domain on a wordlist

### ISSUE THREAD

**Issue by pwnfoo** [Raikia/UhOh365#10]
There are awesome username wordlists out there and I was wondering if a feature can be implemented to use a wordlist and just add a domain prefix to all of it.

Something like `--user-file wordlist --suffix contoso.com` which will add @contoso.com suffix to all usernames.

I can take a stab at it and will send a PR soon :)

**Comment by Raikia** [comment]
This could be a good addition.  Generally I would just add the suffix to my wordlist with vim  (:%s/$/@contoso.com).  If you want to submit a pull request for this, I'll accept it.

**Comment by pwnfoo** [comment]
@Raikia A PR for this is waiting for your review :)

**Comment by Raikia** [comment]
Merged.  Thanks for the pull request!
