### ISSUE TITLE
Office validation versus Outlook validation

### ISSUE THREAD

**Issue by Tr0nB1tch** [Raikia/UhOh365#8]
Emails are found valid even though the company does not use Outlook (OWA) for their email. I've seen this twice now. The companies do use Office in some format though.

**Comment by Raikia** [comment]
Yeah, this process validates if an account has been used for O365.  That includes if it is an account elsewhere in a different MSFT product, not just if its an O365 mailbox.  Really the purpose here is to see if an email is valid _at all_, not necessarily _just_ using o365 email

**Comment by Tr0nB1tch** [comment]
Excellent. Thank you.
